name: build & release

on: push

env:
  MARLIN_DIR: 'marlin'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Trying to check git tag
        run: git -C $MARLIN_DIR describe --tags
      - name: Build artifacts
        run: make
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: '$MARLIN_DIR/.pio/build/**/firmware.bin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}